server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: ueueo-archetype-module-server
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
